name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # اجرای هر روز یک‌بار
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SardarBackend  # یوزرنیم خودت
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
